# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: server-node
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 8080:8080
    links:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://db

  redis:
    image: "redis:alpine"
    container_name: db
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
    expose:
      - 6379
    restart:
      always
